### ISSUE TITLE
Felinmatning vid inloggning

### ISSUE THREAD

**Issue by ghost** [yoyoyonathan/PVT-Grupp4#16]
När man anger ett fel lösenord eller E-mail vid inloggning så “hoppar” sidan tillbaka högst upp, den stannar inte kvar vid formuläret för att logga in.

När man anger ett felaktigt lösenord eller E-mail vid inloggning så kommer felmeddelandet “Fel email/lösenord” upp även under formuläret för “bli medlem”

**Comment by Fortet9000** [comment]
Jag har tittat på detta men inte kunnat lösa det.
