### ISSUE TITLE
Bugs while joining or creating team

### ISSUE THREAD

**Issue by ghost** [yoyoyonathan/PVT-Grupp4#19]
När ett nytt konto är skapat och man skall välja team händer ingenting när man klickar på “Slumpa!”

När man skapar eller går med i ett team vid inloggning så dirigeras man till en sida med slut-URL:en :”../addTeam”. Där man inte kan klicka sig vidare någonstans förutom att skriva en en kod. Gör man det kommer sidan “Action not found” “For request ‘GET /addTeam’”

När man försöker gå med i ett team som är fullt eller inte existerar “skickas” man tillbaka till startsidan, som utloggad. När man försöker logga in igen med sitt skapade konto så kommer felsidan “Oops, an error occured” This exception has been logged with id 6m5hmh937

**Comment by filipsagen** [comment]
När man skapar eller går med i ett team vid inloggning så dirigeras man till en sida med slut-URL:en :”../addTeam”. Där man inte kan klicka sig vidare någonstans förutom att skriva en en kod. Gör man det kommer sidan “Action not found” “For request ‘GET /addTeam’”

**Comment by Fortet9000** [comment]
Allt ska vara fixat nu

**Comment by ghost** [comment]
All bugs solved, closing issue.
